FORMAT: 1A
HOST: http://webgis.nature.cz/aopkrest/eman/

# AOPK ČR - Management API 

## EMAN - detail uživatele [/users/{user_id}]
- informace o uživateli

+ Parameters
    + user_id: 1 (number) - id uživatele 

### Přehled dotazů [GET]

+ Response 200 (application/json)

            {
                "user_id":1,
                "name":"Jm\u00e9no1",
                "surname":"P\u0159\u00edjmen\u00ed1",
                "title_before":"",
                "title_after":"",
                "email":"jmeno1.prijmeni1@nature.cz",
                "activity":1,
                "internal":1,
                "role_ids":"1,2,3"
            }

## EMAN - Výpis rolí [/users/{user_id}/roles/]
- výpis rolí daného uživatele
- admin
- superedit - přidává/edituje smlouvy za projekty přidělené jeho RP
- edit - přidavá/edituje opatření za smlouvy pro své RP
- auditor - všechno vidí, nemůže editovat nic
- read - vidí pouze své RP, nemůže editovat nic

+ Parameters
    + user_id: 1 (number) - id uživatele

### Přehled rolí [GET]

+ Response 200 (application/json)

    + Attributes (array[Role])
    + Attributes (array[Role])


## Eman Činnosti [/activities/]
- vrátí  seznam všech činností - z intranetu - slouží jako číselník
- bude vracet celý číselník

### Přehled činností [GET]

+ Response 200 (application/json)

    + Attributes (array[Activity])
    + Attributes (array[Activity])
    + Attributes (array[Activity])


## EMAN - Seznam projektů [/projects/]
- výpis všech projektů

### Výpis projektů [GET]

+ Response 200 (application/json)

    + Attributes (array[Project])
    + Attributes (array[Project])

## EMAN - Detail projektu [/projects/{proj_id}]

+ Parameters
    + proj_id: 101114 (number) - id projektu 

### Smazání projektu [DELETE]

+ Request 200 (application/json)

        {
            + proj_id: 101114 (number) - id projektu (primární klíč z databáze)
        }

+ Response 201 (application/json)

            {
                + result_id: 0 (number) - výsledek operace 
            }

## EMAN - Projekt Administrovaný [/projects/administer/]
- pro přidání nového projektu

### Přidat nový projekt  [POST]

+ Request 200 (application/json)

    + Attributes (ProjectNew)

+ Response 201 (application/json)

    + Attributes (Project)

## EMAN - Projekt Administrovaný [/projects/administer/{proj_id}]

+ Parameters
    + proj_id: 101114 (number) - id projektu (primární klíč z databáze)

### Změna projektu  [PATCH]

+ Request 200 (application/json)

     + Attributes (ProjectNew)

+ Response 201 (application/json)

     + Attributes (Project)

## EMAN - Projekt z Ekis [/projects/ekis/]
- Přídání a úprava ekis projektu - respektive - interní a kombinovaný projekt
- přidání nového projektu z EKIS - tedy umožňuje přidat pouze projekty které již jsou zadané v aplikaci ekisu
- přidat regionální pracoviště(včetně ústředí), pro daný projekt - tato reg pracoviště budou moci přidávat oblasti a smlouvy
- ekisid - pokud je vyplněné ekisid - tak si api šáhne do view z EKIS s informacema o projektu
- projectType - (1,2,3) interní, kombinovaný, aministrovaný
- Kontrola - může být pouze projectType 1,2


### Přidat projekt [POST]
- přidá nový projekt z DB EKIS
+ Request 200 (application/json)

        {
            + ekis_id: 101478 (number) - kód ekis - interní id z databáze
            + reg_id: 1, 14, 16 (array [number]) - id regionálních pracovišť
            + type: 0  (number) - typ projektu  0/interní - pouze ekis - není možné editovat, 2/kombinovaný - data z ekis i možné přidávání vlastních smluv a oblastí
        }
        
+ Response 201 (application/json)

        {
            + Attributes (Project)
        }


## EMAN - Projekt z Ekis [/projects/ekis/{proj_id}]

+ Parameters
    + proj_id: 101114 (number) - id projektu (primární klíč z databáze)

### Upravit projekt [PATCH]
- úpravy regionálních pracovišť a hlavně možnost nastavit zdali sychronizovat data o projektu a smlouvách z ekis

+ Request 200 (application/json)

        {
            + reg_id: 1, 14, 16 (array [number]) - id regionálních pracovišť
            + ekis_synch: 0 (number) - nastavení zdali se je synchronizace aktivní či nikoliv
            + type: 0  (number) - typ projektu  0/interní - pouze ekis, 2/kombinovaný - ekis i manuál
        }
        
+ Response 201 (application/json)

        {
            + Attributes (Project)
        }


## EMAN - Seznam managementových položek [/ManItems?proj_id={proj_id}&reg_id={reg_id}&code={code}]
- seznam managementových položek (smluv, oblastí) - doplnit filter
- filtrování funguje tak, že musí být vyplněn alespoň jeden parametr + pokud je vybrán projekt, pak je možné hledat pouze regionální pracoviště z projektu a pod...

+ Parameters
    + proj_id: 101114 (number, optional) - id projektu /primární klíč z databáze/
    + reg_id: 12 (number, optional) - id regionálního pracoviště
    + code: PPK-39f/82/19 (string, optional) - řetězec pro vyhledání v kódech dané aplikace


###  výpis managementových položek [GET]

+ Response 200 (application/json)

    + Attributes (array[ManItem])
    + Attributes (array[ManItem])
    + Attributes (array[ManItem])


### Přidat managementovou položku [POST]
- přidá nový projekt z DB EKIS

+ Request 200 (application/json)

        {
            + Attributes (ManItemNew)   
        }
        
+ Response 201 (application/json)

        {
            + Attributes (ManItem)
        }


## EMAN - Detail informací o managemantové položce [/ManItems/{item_id}]
- výpis detatailních infomrací o managamentové položce

+ Parameters
    + item_id: 178788 (number) - id managementové položky

### Změna projektu  [PATCH]

+ Request 200 (application/json)

     + Attributes (ManItemNew)

+ Response 201 (application/json)

     + Attributes (ManItem)


### Vymazat managementovou položku [DELETE]

- proběhne kontrola: Nesmí být položka, která imporovaná z EKIS, a nesmí mít přidané žádná opatření

+ Request 200 (application/json)

        {
            + item_id: 101114 (number) - id managementové položky
        }

+ Response 201 (application/json)

        {
            + result_id: 0 (number) - výsledek operace 
        }


## EMAN - Seznam opatření pro managemetovou položku  [/ManItems/{item_id}/measures]
- výpis přehledu opatření pro danou managementovou položku

### přidání nového opatření [POST]
- přidání nového opatření
- proběhne kontrola: Nesmí být položka, která imporovaná z EKIS, a nesmí mít přidané žádná opatření

+ Request 200 (application/json)

        {
            + item_id: 101114 (number) - id managementové položky
        }

+ Response 201 (application/json)

        {
            + result_id: 0 (number) - výsledek operace
        }

## EMAN - detail informací o opatření  [/ManItems/{item_id}/measures/{measure_id}]
- seznam opatření pro konkrétní managementovou položku

+ Parameters
    + item_id: 178788 (number) - id managementové položky
    + measure_id: 157878 (number) - id managementové položky

### Změna opatření  [PATCH]

+ Request 200 (application/json)

     + Attributes (MeasureNew)

+ Response 201 (application/json)

     + Attributes (Measure)

### Smazání vybraného opatření [DELETE]
- pozor pokud je na to přivázaný zákres/y upozornění

+ Request 200 (application/json)

        {
            + measure_id: 101114 (number) - id projektu (primární klíč z databáze)
        }

+ Response 201 (application/json)

        {
            + result_id: 0 (number) - výsledek operace 
        }


# Data Structures

## Role (object)
Uživatelské role
admin - administruje projekty
superedit - přidává/edituje smlouvy za projekty přidělené jeho RP
edit - přidavá/edituje opatření za smlouvy pro své RP
auditor - všechno vidí, nemůže editovat nic
read - vidí pouze své RP, nemůže editovat nic

### Properties
+ role_id: 1 (number) - id role
+ role_name: Admin (string) - název role

## Activity
činnost - převzané z číselníku činností z intranetu

### Properties
+ activity_id: 1752 (number) - id činnosti
+ activity_name: Výsadba dřevin (string) - název činnosti
+ note: PUPFL podsadba, dosadba dřevin (string) - poznámka
+ category: les (string) - kategorie
+ unit: ks (string)  -jednotka může být i m3

## Project (object)

+ id: 178788 (number) - vniřní id projektu
+ include (ProjectNew)

## ProjectNew (object)

### Properties
+ name: Můj projekt 1 (string) - název projektu
+ code: OKB470058 (string) - kod projektu - zadává se ručně a nebo se získává z EKIS
+ date_from: 27-07-2019 (date, optional) - platnost projektu od, může být prázdné
+ date_to: 27-11-2021  (date, optional) - platnost projektu do, může být prázdné
+ type: 0  (number) - typ projektu  0/interní - pouze ekis, 1/administrovaný - pouze manuální zadání, 2/kombinovaný - je v ekisu, ale je možné také přidávat smlouvy/oblasti manuálně
+ reg_id: 1, 14, 16 (array [number]) - pole id regionálních pracovišť, která mohou smlouvy a činnosti projektu editovat
+ ekis_id: 0 (number, optional)  - id z db EKIS - pouze pokud je projekt z EKIS
+ ekis_synch: 1 (number, optional) - synchronizace dat z EKIS 0 - neaktivní, 1-aktivní


## ManItemNew (object)
"managementová" položka - kombinace smlouvy a oblasti - nová pložka bez ID

### Properties

+ code: PPK-39f/82/19 (string) - kód nebo název oblasti
+ proj_id: 15457 (number) - id projektu
+ subject: Kosení za pařezem, a kolem stromu (string) - struční popis oblasti/předmět smlouvy
+ type: C (string) - typ smlouva/C oblast/A
+ ekis_import:0 (number) -  1/importováno z Ekisu, 0/zadáno manuálně
+ price: 14578 (number, optional) - cena - ve smlouvě povinná u oblasti volitelná
+ contractor: Jirka Petřík (string, optional) - zpracovatel
+ reg_id: 1, 14, 16 (array [number]) - id regionálních pracovišť přidělených ke smlouvě, oblasti - automaticky se přidávají ty co jsou na projektu

## ManItem (object)
"managementová" položka - komplet

### Properties

+ item_id: 178788 (number) - id managementové položky
+ include (ManItemNew)

## Measure

- MeasureNew

### Properties

+ measure_id: 178788 (number) - id_opatření
+ include (MeasureNew)

## MeasureNew (object)

+ id: 178788 (number) - vniřní id projektu
+ include (ProjectNew)

### Properties
+ contract_id: 1577 (number) -  id smlouvy
+ activity_id: 144 (number) - id činnosti
+ activity_cat_id: 18 (number) - kategori činnosti
+ year: 2018 (number) - rok
+ price: 57878.487 (number) - cena
+ amount: 15787,17 (number) - množství
+ note: Odvozit klestí (string) - poznámka