FORMAT: 1A
HOST: http://webgis.nature.cz/aopkrest/eman/

# AOPK ČR - Evidence managementových opatření (EMAN) - BackendAPI

## Uživatel - detail [/users/{user_id}]
- informace o uživateli

+ Parameters
    + user_id: 1 (number) - id uživatele 

### Vypsat uživatele [GET]

+ Response 200 (application/json)

            {
                "user_id":1,
                "name":"Jm\u00e9no1",
                "surname":"P\u0159\u00edjmen\u00ed1",
                "title_before":"",
                "title_after":"",
                "email":"jmeno1.prijmeni1@nature.cz",
                "activity":1,
                "internal":1,
                "role_ids":"1,2,3"
            }

## Uživatel - role [/users/{user_id}/roles/]
- výpis rolí uživatele

+ Parameters
    + user_id: 1 (number) - id uživatele

### Vypsat seznam rolí [GET]

+ Response 200 (application/json)

    + Attributes (array[Role])
    + Attributes (array[Role])

## Činnost - seznam [/activities/]
- vrátí  seznam všech činností - z intranetu - slouží jako číselník

### Vypsat seznam činností [GET]

+ Response 200 (application/json)

    + Attributes (array[Activity])
    + Attributes (array[Activity])
    + Attributes (array[Activity])

## Projekt - seznam [/projects/]
- všechny projekty - administrované, interní i kombinované viz typ projektu

### Vypsat seznam projektů [GET]

+ Response 200 (application/json)

    + Attributes (array[Project])
    + Attributes (array[Project])
    + Attributes (array[Project])

## Projekt - detail [/projects/{proj_id}]

+ Parameters
    + proj_id: 101114 (number) - id projektu 

### Vymazat projekt [DELETE]

+ Request (application/json)

     + Attributes
        + proj_id: 101114 (number) - id projektu primární klíč z databáze

+ Response 200 (application/json)

    + Attributes
        + result_id: 0 (number) - výsledek operace 

## Projekt - administrovaný - seznam [/projects/administer/]
- projekty, které uživatelé zadávájí "manuálně"

### Přidat projekt  [POST]

+ Request (application/json)

    + Attributes (ProjectAdministerNew)

+ Response 200 (application/json)

    + Attributes (Project)

## Projekt - administrovaný - detail [/projects/administer/{proj_id}]

+ Parameters
    + proj_id: 101114 (number) - id projektu (primární klíč z databáze)

### Editovat projekt [PATCH]

+ Request (application/json)

     + Attributes (ProjectAdministerNew)

+ Response 200 (application/json)

     + Attributes (Project)

## Projekt - ekis - seznam  [/projects/ekis/]
- projekty vybírané ze systému ekis 
- Kontrola - může být pouze projectType 1,2

### Přidat projekt [POST]

+ Request (application/json)

    + Attributes (ProjectEkisNew)
        
+ Response 200 (application/json)

    + Attributes (Project)

## Projekt - ekis - detail [/projects/ekis/{proj_id}]

+ Parameters
    + proj_id: 101114 (number) - id projektu (primární klíč z databáze)

### Editovat projekt [PATCH]
- úpravy regionálních pracovišť a hlavně možnost nastavit zdali sychronizovat data o projektu a smlouvách z ekis

+ Request (application/json)

    + Attributes (ProjectEkisNew)

+ Response 200 (application/json)

    + Attributes (Project)

## Managementové položky - seznam [/ManItems?proj_id={proj_id}&reg_id={reg_id}&code={code}]
- seznam managementových položek (smluv, oblastí)

###  Vypsat managementové položky [GET]
- filtrování funguje tak, že musí být vyplněn alespoň jeden parametr + pokud je vybrán projekt, pak je možné hledat pouze regionální pracoviště z projektu a pod...
+ Parameters
    + proj_id: 101114 (number, optional) - id projektu /primární klíč z databáze/
    + reg_id: 12 (number, optional) - id regionálního pracoviště
    + code: PPK-39f/82/19 (string, optional) - řetězec pro vyhledání v kódech dané aplikace

+ Response 200 (application/json)

    + Attributes (array[ManItem])
    + Attributes (array[ManItem])
    + Attributes (array[ManItem])

### Přidat managementovou položku [POST]

+ Request (application/json)

    + Attributes (ManItemNew)   

+ Response 200 (application/json)

    + Attributes (ManItem)

## Managemantové položky - detail [/ManItems/{item_id}]

+ Parameters
    + item_id: 178788 (number) - id managementové položky

### Editovat managementovou položku  [PATCH]

+ Request (application/json)

     + Attributes (ManItemNew)

+ Response 200 (application/json)

     + Attributes (ManItem)

### Smazat managementovou položku [DELETE]

- proběhne kontrola: Nesmí být položka, která je imporovaná z EKIS, a nesmí mít přidané žádná opatření

+ Request (application/json)

    + Attributes
        + item_id: 101114 (number) - id managementové položky

+ Response 200 (application/json)

    + Attributes
        + result_id: 0 (number) - výsledek operace 

## Opatření - seznam [/ManItems/{item_id}/measures]
- výpis seznamu opatření pro danou managementovou položku

+ Parameters
    + item_id: 101114 (number) - id managementové položky

###  Vypsat seznam opatření [GET]

+ Response 200 (application/json)

    + Attributes (array[Measure])
    + Attributes (array[Measure])
    + Attributes (array[Measure])

### Přidat opatření [POST]

+ Request (application/json)

    + Attributes (MeasureNew)

+ Response 200 (application/json)

    + Attributes (Measure)

## Opatření - detail  [/ManItems/{item_id}/measures/{measure_id}]

+ Parameters
    + item_id: 178788 (number) - id managementové položky
    + measure_id: 157878 (number) - id managementové položky

### Editovat opatření  [PATCH]
+ Request (application/json)

    + Attributes (MeasureNew)

+ Response 200 (application/json)

    + Attributes (Measure)

### Smazat opatření [DELETE]
- kontrola zdali nemá zákresy

+ Request (application/json)

    + Attributes
        + measure_id: 101114 (number) - id projektu (primární klíč z databáze)

+ Response 200 (application/json)

    + Attributes
        + result_id: 0 (number) - výsledek operace 

# Data Structures

## Role (object)
Uživatelské role
admin - administruje projekty
superedit - přidává/edituje smlouvy za projekty přidělené jeho RP
edit - přidavá/edituje opatření za smlouvy pro své RP
auditor - všechno vidí, nemůže editovat nic
read - vidí pouze své RP, nemůže editovat nic

### Properties
+ role_id: 1 (number) - id role
+ role_name: Admin (string) - název role

## Activity
činnosti - převzané z číselníku činností z intranetu

### Properties
+ activity_id: 1752 (number) - id činnosti
+ activity_name: Výsadba dřevin (string) - název činnosti
+ note: PUPFL podsadba, dosadba dřevin (string) - poznámka
+ category: les (string) - kategorie
+ unit: ks (string)  -jednotka může být i m3


## ProjectAdministerNew (object)
projekt bez ID

### Properties
+ name: Můj projekt 1 (string) - název projektu
+ code: OKB470058 (string) - kod projektu - zadává se ručně a nebo se získává z EKIS
+ date_from: 27-07-2019 (date, optional) - platnost projektu od, může být prázdné
+ date_to: 27-11-2021  (date, optional) - platnost projektu do, může být prázdné
+ type: 0  (number) - typ projektu  0/interní - pouze ekis, 1/administrovaný - pouze manuální zadání, 2/kombinovaný - je v ekisu, ale je možné také přidávat smlouvy/oblasti manuálně
+ reg_id: 1, 14, 16 (array [number]) - pole id regionálních pracovišť, která mohou smlouvy a činnosti projektu editovat
+ ekis_id: 0 (number, optional)  - id z db EKIS - pouze pokud je projekt z EKIS
+ ekis_synch: 1 (number, optional) - synchronizace dat z EKIS 0 - neaktivní, 1-aktivní

## Project (object)
projekt s id
 
### Properties
+ id: 178788 (number) - vniřní id projektu
+ include (ProjectAdministerNew)

## ProjectEkisNew (object)
projekt z EKIS

### Properties
+ reg_id: 1, 14, 16 (array [number]) - id regionálních pracovišť
+ ekis_synch: 0 (number) - nastavení zdali se je synchronizace aktivní či nikoliv
+ type: 0  (number) - typ projektu  0/interní - pouze ekis, 2/kombinovaný - ekis i manuál

## ManItemNew (object)
"managementová" položka - kombinace smlouvy a oblasti - nová pložka bez ID

### Properties

+ code: PPK-39f/82/19 (string) - kód nebo název oblasti
+ proj_id: 15457 (number) - id projektu
+ subject: Kosení za pařezem, a kolem stromu (string) - struční popis oblasti/předmět smlouvy
+ type: C (string) - typ smlouva/C oblast/A
+ ekis_import:0 (number) -  1/importováno z Ekisu, 0/zadáno manuálně
+ price: 14578 (number, optional) - cena - ve smlouvě povinná u oblasti volitelná
+ contractor: Jirka Petřík (string, optional) - zpracovatel
+ reg_id: 1, 14, 16 (array [number]) - id regionálních pracovišť přidělených ke smlouvě, oblasti - automaticky se přidávají ty co jsou na projektu

## ManItem (object)
"managementová" položka - tedy smlouva nebo oblast

### Properties

+ item_id: 178788 (number) - id managementové položky
+ include (ManItemNew)


## MeasureNew (object)
opatření bez ID

### Properties
+ contract_id: 1577 (number) - id smlouvy
+ activity_id: 144 (number) - id činnosti
+ activity_cat_id: 18 (number) - kategori činnosti
+ year: 2018 (number) - rok
+ price: 57878.487 (number) - cena
+ amount: 15787.17 (number) - množství
+ note: Odvozit klestí (string) - poznámka

## Measure (object)
opatření včetně id

### Properties
+ include MeasureNew
+ measure_id: 178788 (number) - id opatření